workflows:
  native-android:
    name: Native Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference2
    scripts:
      - name: Set Android SDK location
        script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
    triggering:
     events:
       - push
     branch_patterns:
       - pattern: 'gh-readonly-queue/master'
    publishing:
      email:
        recipients:
          - hadesviper46@gmail.com
        notify:
          success: true
          failure: false
